### ISSUE TITLE
Issue when running train_sft.sh

### ISSUE THREAD

**Issue by yunsaijc** [allenai/FineGrainedRLHF#12]
I ran into a problem when running train_sft.sh after finishing all setups. 
The terminal output is as follow:

```
[W socket.cpp:601] [c10d] The IPv6 network addresses of (cernet2.net, 52533) cannot be retrieved (gai error: -5 - No address associated with hostname).
[W socket.cpp:601] [c10d] The IPv6 network addresses of (cernet2.net, 52533) cannot be retrieved (gai error: -5 - No address associated with hostname).
[W socket.cpp:601] [c10d] The IPv6 network addresses of (cernet2.net, 52533) cannot be retrieved (gai error: -5 - No address associated with hostname).
[W socket.cpp:601] [c10d] The IPv6 network addresses of (cernet2.net, 52533) cannot be retrieved (gai error: -5 - No address associated with hostname).
[W socket.cpp:601] [c10d] The IPv6 network addresses of (cernet2.net, 52533) cannot be retrieved (gai error: -5 - No address associated with hostname).
[E socket.cpp:860] [c10d] The client socket has timed out after 1800s while trying to connect to (cernet2.net, 52533).
Traceback (most recent call last):
  File "/home/jc/workspace/FineGrainedRLHF/./sft/run_sft.py", line 480, in <module>
    main()
  File "/home/jc/workspace/FineGrainedRLHF/./sft/run_sft.py", line 190, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/transformers/hf_argparser.py", line 226, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 108, in __init__
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/transformers/training_args.py", line 1115, in __post_init__
    and (self.device.type != "cuda")
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 987, in wrapper
    return func(*args, **kwargs)
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/transformers/training_args.py", line 1475, in device
    return self._setup_devices
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/transformers/utils/generic.py", line 50, in __get__
    cached = self.fget(obj)
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 987, in wrapper
    return func(*args, **kwargs)
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/transformers/training_args.py", line 1460, in _setup_devices
    torch.distributed.init_process_group(backend="nccl", timeout=self.ddp_timeout_delta)
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 754, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 177, in _create_c10d_store
    return TCPStore(
TimeoutError: The client socket has timed out after 1800s while trying to connect to (cernet2.net, 52533).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3785353) of binary: /home/jc/app/anaconda3/envs/rlhf/bin/python
Traceback (most recent call last):
  File "/home/jc/app/anaconda3/envs/rlhf/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jc/app/anaconda3/envs/rlhf/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./sft/run_sft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-18_14:17:20
  host      : cernet2.net
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3785353)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by yunsaijc** [comment]
I find the solution:
add the following item in /etc/hosts:
127.0.0.1 cernet2.net
