### ISSUE TITLE
sft训练时找不到transformers.generation

### ISSUE THREAD

**Issue by Congcong-Song** [allenai/FineGrainedRLHF#5]
Traceback (most recent call last):
  File "/home/inspur/scc/gpt/FineGrainedRLHF/./sft/run_sft.py", line 483, in <module>
    main()
  File "/home/inspur/scc/gpt/FineGrainedRLHF/./sft/run_sft.py", line 265, in main
    model = AutoModelForSeq2SeqLM.from_pretrained(
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 147, in get_class_in_module
Traceback (most recent call last):
  File "/home/inspur/scc/gpt/FineGrainedRLHF/./sft/run_sft.py", line 483, in <module>
    main()
  File "/home/inspur/scc/gpt/FineGrainedRLHF/./sft/run_sft.py", line 265, in main
    module = importlib.import_module(module_path)
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    model = AutoModelForSeq2SeqLM.from_pretrained(
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    model_class = get_class_from_dynamic_module(
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 147, in get_class_in_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/inspur/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 23, in <module>
    module = importlib.import_module(module_path)
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    from transformers.generation.logits_process import LogitsProcessor
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
: No module named 'transformers.generation'
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/inspur/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 23, in <module>
    from transformers.generation.logits_process import LogitsProcessor
ModuleNotFoundError: No module named 'transformers.generation'
Traceback (most recent call last):
  File "/home/inspur/scc/gpt/FineGrainedRLHF/./sft/run_sft.py", line 483, in <module>
Traceback (most recent call last):
  File "/home/inspur/scc/gpt/FineGrainedRLHF/./sft/run_sft.py", line 483, in <module>
    main()
  File "/home/inspur/scc/gpt/FineGrainedRLHF/./sft/run_sft.py", line 265, in main
    model = AutoModelForSeq2SeqLM.from_pretrained(
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    main()
  File "/home/inspur/scc/gpt/FineGrainedRLHF/./sft/run_sft.py", line 265, in main
    model_class = get_class_from_dynamic_module(
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
    model = AutoModelForSeq2SeqLM.from_pretrained(
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 147, in get_class_in_module
        model_class = get_class_from_dynamic_module(module = importlib.import_module(module_path)

  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    return get_class_in_module(class_name, final_module.replace(".py", ""))  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 147, in get_class_in_module
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    module = importlib.import_module(module_path)
  File "/home/inspur/anaconda3/envs/rlhf_py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "/home/inspur/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    from transformers.generation.logits_process import LogitsProcessor
ModuleNotFoundError  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
: No module named 'transformers.generation'
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/inspur/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 23, in <module>
    from transformers.generation.logits_process import LogitsProcessor
ModuleNotFoundError: No module named 'transformers.generation'

**Comment by Congcong-Song** [comment]
找到问题了，是因为训练了chatglm2，里面的代码modeling_chatglm的代码需要的transformers的版本和rlhf的不兼容
